### PR TITLE
Fix SpriteFrame Subimage Transfer

### LINKED ISSUE #304: Image duplication then edit edits wrong image
To reproduce:  
1. Have an image in a sprite.  
2. Select the first image.
3. Copy and paste that image into the sprite to duplicate it.  
4. Double click the last image to edit it.  
5. Save the image.  
6. The image will be saved to the image that is before the selected image, rather than to the selected image.

### PR DESCRIPTION
**Pull request by RobertBColton**
This fixes the main part of #304. I managed to track it down to paste being a shallow copy of the clipboard contents, hence, whenever the pasted duplicate subframes were edited, they were actually editing the same subimage. This bug only occurred if you had pasted the subimage more than one time, because each subsequent paste was an additional shallow copy of the same clipboard contents.

There seems to be no need to do a deep copy for cut or copy however, as the following steps seem to indicate:
1) Create a new project
2) Create a new sprite
3) Add a subimage
4) Copy the new subimage to your clipboard
5) Now edit the subimage (just fill it in with a solid color)
6) Save the subimage
7) Now paste the original subimage copied from your clipboard

LGM has the correct behavior (that the pasted subimage should be the way the subimage was when copied) for this even before these changes.

### CODE REVIEW

File: org/lateralgm/subframes/SpriteFrame.java [hunk 1]
```diff
@@ -1269,6 +1268,10 @@ else if (cmd.endsWith(".PASTE"))
 					LGM.showDefaultExceptionHandler(e);
 					}
 				imageChanged = true;
+				for (int i = 0; i < images.bi.size(); i++)
+					{
+					images.bi.set(i, Util.cloneImage(images.bi.get(i)));
```
Comment (JoshDreamland) [inline org/lateralgm/subframes/SpriteFrame.java]: You are discarding the original copy of these images. So even the first time you go to make a paste, you're copying them. Please just call `res.subImages.add(Util.cloneImage(images.bi.get(i)));`.

Comment (RobertBColton) [reply org/lateralgm/subframes/SpriteFrame.java]: Good point.

File: org/lateralgm/subframes/SpriteFrame.java [hunk 2]
```diff
@@ -1269,8 +1268,11 @@ else if (cmd.endsWith(".PASTE"))
 					LGM.showDefaultExceptionHandler(e);
 					}
 				imageChanged = true;
-				res.subImages.addAll(pos + 1,images.bi);
-				subList.setSelectionInterval(pos + 1,pos + images.bi.size());
+				for (int i = 0; i < images.bi.size(); i++)
+					{
+					res.subImages.add(pos + i, Util.cloneImage(images.bi.get(i)));
+					}
+				subList.setSelectionInterval(pos, pos + images.bi.size() - 1);
```
Comment (JoshDreamland) [inline org/lateralgm/subframes/SpriteFrame.java]: Why did this change?

Comment (RobertBColton) [reply org/lateralgm/subframes/SpriteFrame.java]: Say you have the first subimage selected when you hit paste, the subimage you are pasting should take its place, and the one that was there should be moved down one. Previously it would paste one after the current selection. So I basically just undid that. Don't forget, I'm the one who wrote the original code for this part here.
